--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2024-10-30 21:16:33

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16644)
-- Name: device; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.device (
    id bigint NOT NULL,
    mhec integer NOT NULL,
    address character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.device OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16643)
-- Name: device_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.device ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16651)
-- Name: user_ref; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_ref (
    user_id bigint NOT NULL,
    user_name character varying(255) NOT NULL
);


ALTER TABLE public.user_ref OWNER TO postgres;


--
-- TOC entry 4639 (class 2606 OID 16650)
-- Name: device device_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_pkey PRIMARY KEY (id);


--
-- TOC entry 4641 (class 2606 OID 16655)
-- Name: user_ref user_ref_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_ref
    ADD CONSTRAINT user_ref_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4642 (class 2606 OID 16656)
-- Name: device fk59ml053k8nl7jglwg7k5hit5g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT fk59ml053k8nl7jglwg7k5hit5g FOREIGN KEY (user_id) REFERENCES public.user_ref(user_id);


-- Completed on 2024-10-30 21:16:33

--
-- PostgreSQL database dump complete
--

