--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2024-11-26 19:16:43

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16688)
-- Name: device_ref; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.device_ref (
    mhec integer NOT NULL,
    device_id bigint NOT NULL
);


ALTER TABLE public.device_ref OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16694)
-- Name: monitor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.monitor (
    measurement_value double precision NOT NULL,
    device_id bigint NOT NULL,
    id bigint NOT NULL,
    "timestamp" bigint NOT NULL
);


ALTER TABLE public.monitor OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16693)
-- Name: monitor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.monitor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monitor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4794 (class 0 OID 0)
-- Dependencies: 216
-- Name: monitor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.monitor_id_seq', 32, true);


--
-- TOC entry 4639 (class 2606 OID 16692)
-- Name: device_ref device_ref_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device_ref
    ADD CONSTRAINT device_ref_pkey PRIMARY KEY (device_id);


--
-- TOC entry 4641 (class 2606 OID 16698)
-- Name: monitor monitor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monitor
    ADD CONSTRAINT monitor_pkey PRIMARY KEY (id);


--
-- TOC entry 4642 (class 2606 OID 16699)
-- Name: monitor fkmjgqig7dgwb4anpyxlfhvcop; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monitor
    ADD CONSTRAINT fkmjgqig7dgwb4anpyxlfhvcop FOREIGN KEY (device_id) REFERENCES public.device_ref(device_id) ON DELETE CASCADE;


-- Completed on 2024-11-26 19:16:43

--
-- PostgreSQL database dump complete
--

